export enum GameEvent {
	LoadMap,
	LoadMapCompleted,
	UnitsInitialized,
	GridCellActivated,
	UnitSelected,
	UnitWaitActionSelected,
	UnitMoveActionSelected,
	UnitMove,
	UnitMoveCompleted,
	UnitAttackActionSelected,
	UnitAttack,
	UnitAttackCompleted,
	CancelAction,
	TurnStart,
	TurnComplete,
}